name: ECS CI/CD pipeline 

on: 
push:
  branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # basic settings
      - name: Checkout~!
        uses: actions/checkout@v3
      - name: Setup Python~!
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependancies~!
        run: |
          python -m pip install --upgrade pip 
          pip install -r requirements.txt

      # CI
      - name: Login to Dockerhub~!
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
      - name: Build and Push Docker Image~!
        env:
          NAME: ${{secrets.DOCKERHUB_USERNAME}}
          REPO: for_assignments
        run: |
          docker build -t $NAME/$REPO:latest .
          docker push $NAME/$REPO:latest

      # CD
      - name: NEW JOB
        run: |
         echo "MEOW MEOW" 



